[package]
name = "encry"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.1.0"
sha3 = "0.10.8"

[profile.release]
strip = true
opt-level = "z"
lto = true